# Generated by Django 6.0.3 on 2026-03-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_socios', '0006_socios_fecha_modificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=30)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('socio_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_socios.socios')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bienes_inmueble.tipoinmueble')),
            ],
            options={
                'db_table': 'inmuebles',
            },
        ),
    ]
