# Generated by Django 6.0.3 on 2026-03-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bienes_inmueble', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoinmueble',
            table='tipo_inmueble',
        ),
    ]
