# Generated by Django 6.0.3 on 2026-03-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bienes_inmueble', '0002_alter_tipoinmueble_table'),
        ('app_socios', '0009_alter_personasrelacionadassocio_denominacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='codigo_socio_asociado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_socios.codigosasociadossocio'),
            preserve_default=False,
        ),
    ]
