# Generated by Django 6.0.3 on 2026-03-23 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bienes_inmueble', '0003_inmuebles_codigo_socio_asociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnlaceSocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=30)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_enlace_socio',
            },
        ),
        migrations.AlterModelOptions(
            name='inmuebles',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='tipo_enlace_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bienes_inmueble.tipoenlacesocio'),
        ),
    ]
