# Generated by Django 6.0.3 on 2026-03-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstadosCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=15)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_estados_civil',
            },
        ),
        migrations.CreateModel(
            name='TipoSexos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=15)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_sexos',
            },
        ),
        migrations.CreateModel(
            name='TipoSocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=15)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_socios',
            },
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=150)),
                ('domicilio', models.CharField(blank=True, max_length=180, null=True)),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_socios.tipoestadoscivil')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_socios.tiposexos')),
                ('tipo_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_socios.tiposocio')),
            ],
            options={
                'db_table': 'socios',
            },
        ),
    ]
