# Generated by Django 6.0.3 on 2026-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
