# Generated by Django 6.0.3 on 2026-03-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0002_socios_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socios',
            name='numero',
        ),
    ]
