# Generated by Django 6.0.3 on 2026-03-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0003_remove_socios_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socios',
            name='nombre',
        ),
        migrations.AddField(
            model_name='socios',
            name='apellidos',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socios',
            name='nombres',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
