# Generated by Django 6.0.3 on 2026-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0004_remove_socios_nombre_socios_apellidos_socios_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='dni',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
