# Generated by Django 6.0.3 on 2026-03-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0005_socios_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
