# Generated by Django 6.0.3 on 2026-03-21 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0006_socios_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='numero_contacto',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.CreateModel(
            name='CodigosAsociadosSocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('socio_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_socios.socios')),
            ],
            options={
                'db_table': 'codigos_asociados_socio',
            },
        ),
        migrations.CreateModel(
            name='PersonasRelacionadasSocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=10)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('socio_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_socios.socios')),
            ],
            options={
                'db_table': 'personas_relacionadas_socio',
            },
        ),
    ]
