# Generated by Django 6.0.3 on 2026-03-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0007_socios_numero_contacto_codigosasociadossocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personasrelacionadassocio',
            name='denominacion',
            field=models.CharField(max_length=35),
        ),
    ]
