# Generated by Django 6.0.3 on 2026-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0008_alter_personasrelacionadassocio_denominacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personasrelacionadassocio',
            name='denominacion',
            field=models.CharField(max_length=40),
        ),
    ]
