# Generated by Django 6.0.3 on 2026-03-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0009_alter_personasrelacionadassocio_denominacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='numero_contacto',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
