# Generated by Django 6.0.3 on 2026-03-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0010_alter_socios_numero_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='centro_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='distrito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='grado_instruccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='numero_contacto_adicional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='profesion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
