# Generated by Django 6.0.3 on 2026-03-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0011_socios_centro_trabajo_socios_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFamiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=15)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_familiar',
            },
        ),
        migrations.AddField(
            model_name='personasrelacionadassocio',
            name='es_socio',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personasrelacionadassocio',
            name='tipo_familiar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_socios.tipofamiliar'),
            preserve_default=False,
        ),
    ]
