# Generated by Django 6.0.3 on 2026-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0012_tipofamiliar_personasrelacionadassocio_es_socio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='apellidos',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='socios',
            name='nombres',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
