# Generated by Django 6.0.3 on 2026-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0013_alter_socios_apellidos_alter_socios_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
